### ISSUE TITLE
No connection anymore

### ISSUE THREAD

**Issue by ghost** [jikelmon/UFOLEDController#1]
Hey,

i was very happy to find your C# library to control my LEDs in my own homeautomation system via tcp.
I started with your WinForms sample and it worked! 

After 2 hours I wasnt able to control the LEDs anymore.
My iPhone App is still working, the IP adress is the same.
I restarted all devices, i took your winforms sample again... but it does not work anymore.

Do you have any idea what could be wrong?

[Edit: You need to set "Brightness" to 100. Otherwise you cannot use toggle or on/off]

**Comment by jikelmon** [comment]
Strange behaviour but i am glad you found this workaround. 

Maybe you are using a controller with a new firmware version and/or the manufacturer changed the protocol. I only own the v1 and v3 of the ufo controller so if you could upload a tcp sniff from your iphone app via wireshark for example we could update the library for unviersal usage :)

**Comment by ghost** [comment]
Yep, i think it is because of my white led stripe. I do not use RGB.

I extended your code by adding a "DimmWhiteStripe"-Method to fix this problem.
